In [1]:
import numpy as np

a = np.array([i for i in np.arange(2,11)])
print(a)


[ 2  3  4  5  6  7  8  9 10]


In [2]:
z = np.zeros((4,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
o = np.ones((4,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
f = np.full((3,3), 5)
print(f)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [6]:
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
r = np.random.random((3,2))  # (wiersze, kolumny)  
print(r)

[[0.71978251 0.24373657]
 [0.1750439  0.17170832]
 [0.13929432 0.13344748]]


In [12]:
print(type(r))
print(r.shape)
print(r.dtype)

<class 'numpy.ndarray'>
(3, 2)
float64
